import multiprocessing

import httpx

SUCCESS_CODE = "Success"

DEFAULT_DATABASE_DB = "llmops"
DEFAULT_DATABASE_HOST = "127.0.0.1"
DEFAULT_DATABASE_PORT = "5432"
DEFAULT_DATABASE_SCHEMA = "public"
DEFAULT_DATABASE_USER = "llmops"

DEBUG_MODE = False

DEFAULT_LOGGER_LEVEL = "INFO"

DEFAULT_SQLALCHEMY_POOL_SIZE = multiprocessing.cpu_count() * 2 - 1
DEFAULT_SQLALCHEMY_POOL_MAX_OVERFLOW = DEFAULT_SQLALCHEMY_POOL_SIZE // 2
DEFAULT_SQLALCHEMY_POOL_RECYLE = 60 * 60
DEFAULT_SQLALCHEMY_POOL_TIMEOUT = 5 * 60
DEFAULT_SQLALCHEMY_ECHO = False

DEFAULT_CORS_ALLOW_ORIGINS = "127.0.0.1:3000,localhost:3000"
DEFAULT_CORS_ALLOW_CREDENTIALS = True
DEFAULT_CORS_ALLOW_METHODS = "*"
DEFAULT_CORS_ALLOW_HEADERS = "*"
DEFAULT_CORS_EXPOSE_HEADERS = ""
DEFAULT_CORS_MAX_AGE = 10 * 60

DEFAULT_REDIS_USER_NAME = "llmops"
DEFAULT_REDIS_HOST = "127.0.0.1"
DEFAULT_REDIS_PORT = "6379"
DEFAULT_REDIS_DB = 0

DEFAULT_ACCESS_TOKEN_EXPIRE = 60 * 60
DEFAULT_REFRESH_TOKEN_EXPIRE = 30 * 24 * 60 * 60

DEFAULT_ARK_MAX_RETRIES = 2
DEFAULT_ARK_TIMEOUT_SECONDS = 600.0
DEFAULT_ARK_CONNECT_TIMEOUT_SECONDS = 60.0
# default timeout is 1 minutes
DEFAULT_ARK_TIMEOUT = httpx.Timeout(
    timeout=DEFAULT_ARK_TIMEOUT_SECONDS, connect=DEFAULT_ARK_CONNECT_TIMEOUT_SECONDS
)


DEFAULT_RABBITMQ_USERNAME = "llmops"
DEFAULT_RABBITMQ_HOST = "127.0.0.1"
DEFAULT_RABBITMQ_PORT = "5672"
DEFAULT_RABBITMQ_VHOST = "llmops"

DEFAULT_CELERY_BACKEND_DATABASE_HOST = "127.0.0.1"
DEFAULT_CELERY_BACKEND_DATABASE_PORT = "5432"
DEFAULT_CELERY_BACKEND_DATABASE_DB = "llmops"
DEFAULT_CELERY_BACKEND_DATABASE_USER = "public"
DEFAULT_CELERY_BACKEND_DATABASE_SCHEMA = "llmops"
DEFAULT_CELERY_BACKEND_SQLALCHEMY_ECHO = False

DEFAULT_CELERY_BACKEND_SQLALCHEMY_POOL_SIZE = multiprocessing.cpu_count() * 2 - 1
DEFAULT_CELERY_BACKEND_SQLALCHEMY_POOL_MAX_OVERFLOW = DEFAULT_SQLALCHEMY_POOL_SIZE // 2
DEFAULT_CELERY_BACKEND_SQLALCHEMY_POOL_RECYLE = 60 * 60
DEFAULT_CELERY_BACKEND_SQLALCHEMY_POOL_TIMEOUT = 5 * 60
DEFAULT_WORKER_PREFETCH_MULTIPLIER = 4
DEFAULT_WORKER_MAX_TASKS_PER_CHILD = 100
DEFAULT_RESULT_EXPIRES = 15 * 24 * 60 * 60
