import multiprocessing

SUCCESS_CODE = "Success"

DEFAULT_DATABASE_DB = "llmops"
DEFAULT_DATABASE_HOST = "127.0.0.1"
DEFAULT_DATABASE_PORT = "5432"
DEFAULT_DATABASE_SCHEMA = "public"

DEBUG_MODE = False

DEFAULT_LOGGER_LEVEL = "INFO"

DEFAULT_SQLALCHEMY_POOL_SIZE = multiprocessing.cpu_count() * 2 - 1
DEFAULT_SQLALCHEMY_POOL_MAX_OVERFLOW = DEFAULT_SQLALCHEMY_POOL_SIZE // 2
DEFAULT_SQLALCHEMY_POOL_RECYLE = 60 * 60
DEFAULT_SQLALCHEMY_POOL_TIMEOUT = 5 * 60
DEFAULT_SQLALCHEMY_ECHO = False

DEFAULT_CORS_ALLOW_ORIGINS = "127.0.0.1:3000,localhost:3000"
DEFAULT_CORS_ALLOW_CREDENTIALS = True
DEFAULT_CORS_ALLOW_METHODS = "*"
DEFAULT_CORS_ALLOW_HEADERS = "*"
DEFAULT_CORS_EXPOSE_HEADERS = ""
DEFAULT_CORS_MAX_AGE = 10 * 60

DEFAULT_REDIS_USER_NAME = "llmops"
DEFAULT_REDIS_HOST = "127.0.0.1"
DEFAULT_REDIS_PORT = "6379"
DEFAULT_REDIS_DB = 0

DEFAULT_ACCESS_TOKEN_EXPIRE = 60 * 60
DEFAULT_REFRESH_TOKEN_EXPIRE = 30 * 24 * 60 * 60
