"""角色表

Revision ID: 03d9e296446a
Revises: 68543f8c90b3
Create Date: 2025-06-19 16:28:33.980006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d9e296446a'
down_revision: Union[str, None] = '68543f8c90b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['delete_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_role_delete_at'), 't_role', ['delete_at'], unique=False)
    op.create_index(op.f('ix_t_role_name'), 't_role', ['name'], unique=False)
    op.create_index(op.f('ix_t_role_title'), 't_role', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_role_title'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_name'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_delete_at'), table_name='t_role')
    op.drop_table('t_role')
    # ### end Alembic commands ###
