"""action添加路径和方法

Revision ID: 074bb0bcb14e
Revises: 03d9e296446a
Create Date: 2025-06-19 17:40:34.670252

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074bb0bcb14e"
down_revision: Union[str, None] = "03d9e296446a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE TYPE actionmethod AS ENUM ('get', 'post', 'put', 'patch', 'delete', 'options', 'head')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("t_action", sa.Column("path", sa.String(length=200), nullable=False))
    op.add_column(
        "t_action",
        sa.Column(
            "method",
            sa.Enum(
                "get", "post", "put", "patch", "delete", "options", "head", name="actionmethod"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("t_action", "method")
    op.execute("DROP TYPE actionmethod")
    op.drop_column("t_action", "path")
    # ### end Alembic commands ###
