"""casbin

Revision ID: 23142990bd04
Revises: 567ee1866ad2
Create Date: 2025-06-17 21:38:17.320274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23142990bd04'
down_revision: Union[str, None] = '567ee1866ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('ptype', sa.String(length=255), nullable=False),
    sa.Column('v0', sa.String(length=255), nullable=False),
    sa.Column('v1', sa.String(length=255), nullable=False),
    sa.Column('v2', sa.String(length=255), nullable=False),
    sa.Column('v3', sa.String(length=255), nullable=False),
    sa.Column('v4', sa.String(length=255), nullable=False),
    sa.Column('v5', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ptype', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
