"""action name unique

Revision ID: 29b81ff47485
Revises: 074bb0bcb14e
Create Date: 2025-06-20 01:09:31.588919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b81ff47485'
down_revision: Union[str, None] = '074bb0bcb14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_action_name'), table_name='t_action')
    op.create_index(op.f('ix_t_action_name'), 't_action', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_action_name'), table_name='t_action')
    op.create_index(op.f('ix_t_action_name'), 't_action', ['name'], unique=False)
    # ### end Alembic commands ###
