"""插件相关表

Revision ID: 2a5488ce0dc2
Revises: bb0e220bb3b9
Create Date: 2025-06-06 02:36:16.599455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5488ce0dc2'
down_revision: Union[str, None] = 'bb0e220bb3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_plugin_provider',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['delete_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_plugin_provider_delete_at'), 't_plugin_provider', ['delete_at'], unique=False)
    op.create_index(op.f('ix_t_plugin_provider_name'), 't_plugin_provider', ['name'], unique=True)
    op.create_table('t_plugin',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['delete_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['t_plugin_provider.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_plugin_delete_at'), 't_plugin', ['delete_at'], unique=False)
    op.create_index(op.f('ix_t_plugin_name'), 't_plugin', ['name'], unique=False)
    op.create_index(op.f('ix_t_plugin_title'), 't_plugin', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_plugin_title'), table_name='t_plugin')
    op.drop_index(op.f('ix_t_plugin_name'), table_name='t_plugin')
    op.drop_index(op.f('ix_t_plugin_delete_at'), table_name='t_plugin')
    op.drop_table('t_plugin')
    op.drop_index(op.f('ix_t_plugin_provider_name'), table_name='t_plugin_provider')
    op.drop_index(op.f('ix_t_plugin_provider_delete_at'), table_name='t_plugin_provider')
    op.drop_table('t_plugin_provider')
    # ### end Alembic commands ###
