"""知识库相关表约束

Revision ID: 3cc53bfb4156
Revises: 4d3331f2be7d
Create Date: 2025-07-04 16:02:26.716935

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cc53bfb4156"
down_revision: Union[str, None] = "4d3331f2be7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("t_knowledge_document", sa.Column("knowledge_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "t_knowledge_document", "t_knowledge", ["knowledge_id"], ["id"])
    op.add_column("t_retrieval_record_chunks", sa.Column("chunck_text", sa.Text(), nullable=False))
    op.create_foreign_key(
        None, "t_retrieval_record_chunks", "t_retrieval_record", ["record_id"], ["id"]
    )
    op.create_foreign_key(
        None, "t_retrieval_record_chunks", "t_knowledge", ["knowledge_id"], ["id"]
    )
    op.create_foreign_key(
        None, "t_retrieval_record_chunks", "t_knowledge_document", ["document_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "t_retrieval_record_chunks", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "t_retrieval_record_chunks", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "t_retrieval_record_chunks", type_="foreignkey")  # type: ignore
    op.drop_column("t_retrieval_record_chunks", "chunck_text")
    op.drop_constraint(None, "t_knowledge_document", type_="foreignkey")  # type: ignore
    op.drop_column("t_knowledge_document", "knowledge_id")
    # ### end Alembic commands ###
