"""菜单软删除

Revision ID: 567ee1866ad2
Revises: af2bb25991c2
Create Date: 2025-06-12 11:33:50.231357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567ee1866ad2'
down_revision: Union[str, None] = 'af2bb25991c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_menu', sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('t_menu', sa.Column('delete_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_t_menu_delete_at'), 't_menu', ['delete_at'], unique=False)
    op.create_foreign_key(None, 't_menu', 't_user', ['delete_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_menu', type_='foreignkey')
    op.drop_index(op.f('ix_t_menu_delete_at'), table_name='t_menu')
    op.drop_column('t_menu', 'delete_by')
    op.drop_column('t_menu', 'delete_at')
    # ### end Alembic commands ###
