"""casbin column nullable

Revision ID: 7e4c2dad874b
Revises: e0c7da2809a3
Create Date: 2025-06-23 15:16:21.579734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4c2dad874b'
down_revision: Union[str, None] = 'e0c7da2809a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casbin_rule', 'v0',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v4',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v5',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casbin_rule', 'v5',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v4',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v0',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
