"""菜单相关表

Revision ID: af2bb25991c2
Revises: aac351c6383e
Create Date: 2025-06-06 12:14:47.836508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2bb25991c2'
down_revision: Union[str, None] = 'aac351c6383e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_menu',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('icon_filled', sa.String(length=100), nullable=True),
    sa.Column('menu_type', sa.Enum('default', 'discover', 'manage', name='menutype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_menu_name'), 't_menu', ['name'], unique=True)
    op.create_index(op.f('ix_t_menu_title'), 't_menu', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_menu_title'), table_name='t_menu')
    op.drop_index(op.f('ix_t_menu_name'), table_name='t_menu')
    op.drop_table('t_menu')
    # ### end Alembic commands ###
