"""add knowledge document process status

Revision ID: b529b6344784
Revises: bdd9ca7799cc
Create Date: 2025-07-28 17:39:40.647678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b529b6344784'
down_revision: Union[str, None] = 'bdd9ca7799cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_knowledge_document', sa.Column('process_status', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_knowledge_document', 'process_status')
    # ### end Alembic commands ###
