"""字段名称修改

Revision ID: bdd9ca7799cc
Revises: 3cc53bfb4156
Create Date: 2025-07-08 13:42:31.866820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd9ca7799cc'
down_revision: Union[str, None] = '3cc53bfb4156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_retrieval_record_chunks', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.drop_column('t_retrieval_record_chunks', 'chunck_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_retrieval_record_chunks', sa.Column('chunck_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('t_retrieval_record_chunks', 'chunk_text')
    # ### end Alembic commands ###
