"""menu name not unique

Revision ID: e0c7da2809a3
Revises: 29b81ff47485
Create Date: 2025-06-23 12:45:55.662828

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0c7da2809a3"
down_revision: Union[str, None] = "29b81ff47485"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "t_action", ["path", "method"])
    op.drop_index(op.f("ix_t_menu_name"), table_name="t_menu")
    op.create_index(op.f("ix_t_menu_name"), "t_menu", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_t_menu_name"), table_name="t_menu")
    op.create_index(op.f("ix_t_menu_name"), "t_menu", ["name"], unique=True)
    op.drop_constraint(None, "t_action", type_="unique")
    # ### end Alembic commands ###
